# Generated by Django 5.2.3 on 2025-07-02 02:47

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='DashboardPreference',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('show_low_stock_first', models.BooleanField(default=True)),
                ('items_per_page', models.PositiveIntegerField(default=20)),
                ('preferred_view', models.CharField(choices=[('list', 'List View'), ('grid', 'Grid View')], default='list', max_length=10)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='dashboard_preference', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
